import { Montserrat } from "next/font/google";
import "./globals.css";
import ProviderStore from "@/store/ProviderStore";
import { ToastContainer } from "react-toastify";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer/>
        <ProviderStore>
          {children}
        </ProviderStore>
      </body>
    </html>
  );
}
